recurring:
  - title: "ğŸ‘‘"
    repeat: 1
    people:
      - ["estelle.jpg"]
      - ["josephine.jpg"]
  - title: "ğŸ½"
    repeat: 1
    people:
      - ["josephine.jpg"]
      - ["estelle.jpg"]
  - title: "ğŸ•"
    repeat: 1
    people:
      - ["estelle.jpg"]
      - ["josephine.jpg"]

countdowns:
  - image: "snae.jpg"
    title: "ğŸ‚"
    date: "05/29"
  - image: "jessica.jpg"
    title: "ğŸ‚"
    date: "01/31"
  - image: "estelle.jpg"
    title: "ğŸ‚"
    date: "03/04"
  - image: "caspar.jpg"
    title: "ğŸ‚"
    date: "03/09"
  - image: "josephine.jpg"
    title: "ğŸ‚"
    date: "03/21"
  - image: ""
    title: "ğŸ‡¸ğŸ‡ª"
    date: "7/25"
  - image: ""
    title: "ğŸ"
    date: "9/23"
  - image: ""
    title: "â„ï¸"
    date: "12/21"
  - image: ""
    title: "ğŸŒ¸ï¸"
    date: "3/20"
  - image: ""
    title: "ğŸ„"
    date: "12/24"
  - image: ""
    title: "ğŸ–ï¸"
    date: "07/18"
  - image: ""
    title: "â€ğŸ«ï¸"
    date: "09/02"
  - image: ""
    title: "â¤ï¸ğŸ’›"
    date: "09/14"
  - image: ""
    title: "ğŸ‡¬ğŸ‡§"
    date: "10/20"