recurring:
  - title: "ğŸ‘‘"
    repeat: 1
    choices:
      - ["estelle.jpg"]
      - ["josephine.jpg"]
  - title: "ğŸ½"
    repeat: 1
    choices:
      - ["josephine.jpg"]
      - ["estelle.jpg"]
  - title: "ğŸ•"
    repeat: 1
    choices:
      - ["estelle.jpg"]
      - ["josephine.jpg"]
  - title: "ğŸ¿"
    repeat: 1
    choices:
      - ["ğŸ‡©ğŸ‡ª"]
      - ["ğŸ‡¬ğŸ‡§"]



countdowns:
  - image: "snae.jpg"
    title: "ğŸ‚"
    date: "05/29"
  - image: "jessica.jpg"
    title: "ğŸ‚"
    date: "01/31"
  - image: "estelle.jpg"
    title: "ğŸ‚"
    date: "03/04"
  - image: "caspar.jpg"
    title: "ğŸ‚"
    date: "03/09"
  - image: "josephine.jpg"
    title: "ğŸ‚"
    date: "03/21"
  - image: ""
    title: "ğŸ„"
    date: "12/24"
  - image: ""
    title: "ğŸ…"
    date: "12/24"
  - image: ""
    title: "ğŸ‡ºğŸ‡¦"
    date: "01/15"
