recurring:
  - title: "ğŸ‘‘"
    repeat: 1
    people:
      - ["estelle.jpg"]
      - ["josephine.jpg"]
  - title: "ğŸ½"
    repeat: 1
    people:
      - ["josephine.jpg"]
      - ["estelle.jpg"]
  - title: "ğŸ¶"
    repeat: 1
    people:
      - ["estelle.jpg"]
      - ["josephine.jpg"]

countdowns:
  - image: "jessica.jpg"
    title: "ğŸ‚"
    date: "01/31"
  - image: "estelle.jpg"
    title: "ğŸ‚"
    date: "03/04"
  - image: "caspar.jpg"
    title: "ğŸ‚"
    date: "03/09"
  - image: "josephine.jpg"
    title: "ğŸ‚"
    date: "03/21"
  - image: ""
    title: "ğŸ‡¸ğŸ‡ªâ›´ï¸"
    date: "7/21"
  - image: ""
    title: "ğŸ"
    date: "9/23"
  - image: ""
    title: "â„ï¸"
    date: "12/21"
  - image: ""
    title: "ğŸŒ¸ï¸"
    date: "3/20"
  - image: ""
    title: "ğŸ„"
    date: "12/24"